### ISSUE TITLE
Adding a "feature group" tag?

### ISSUE THREAD

**Issue by MikkelStaerkDickenson** [vestas-digital-employee-tools/business-governance#21]
I expect I will be using the tag "enhancement" alot in here :-) .... however, could it make sense to be able to combine this tag with a tag for the type of feature, e.g. corresponting/simmilar to the "Features" we have in ADO?

![image](https://github.com/vestas-digital-employee-tools/business-governance/assets/148050213/dfed664b-9d99-4580-b145-1523429d6772)

**Comment by allanhvam** [comment]
We can make "enhancement: feature-name" labels if needed.
