### ISSUE TITLE
Missing context menu - post here?

### ISSUE THREAD

**Issue by MikkelStaerkDickenson** [vestas-digital-employee-tools/business-governance#22]
Hi both
Erika doesn't see context menu on details view in BusGov. Should I report this here?

**Comment by MikkelStaerkDickenson** [comment]
Not sure whether this bug belongs here or on ADO....

**Comment by DocDoo** [comment]
> Not sure whether this bug belongs here or on ADO....
Let's discuss tomorrow, but I think it hinges on which support solution we agree. I'll make sure the topic is on the agenda.

**Comment by allanhvam** [comment]
By default the solution gets field tooltips (context menu) from the descriptions on the fields. This can be language dependent if configured on SharePoint. To make sure the same description is shown in all languages, the description can be moved to the description attribute in the json-configuration.
